-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgY4sAJjanaUgMVDXS
QgHp+BD/9X3qky0mYG3sQsVISKKgCgYIKoZIzj0DAQehRANCAASDnrkt7aVR3Jeu
vN8kBENMlqf0Z6antJRGHw3vnKEZf6Goypn/qz+hSxvzhhs/+9YPTjModGu6ljmy
akX/x+B6
-----END PRIVATE KEY-----